#!/bin/sh -x

mkdir -p /local/postgresql-db-backups/data

touch /local/postgresql-db-backups
find /local/postgresql-db-backups/data/ -type f -mtime +5 -print -exec rm -f {} \;

mkdir /local/postgresql-db-backups/data/dummy$$
find /local/postgresql-db-backups/data/* -depth -type d -exec rmdir {} \; >/dev/null 2>&1
